### ISSUE TITLE
Broken due to site change

### ISSUE THREAD

**Issue by kokangit** [kodi-svtplay/xbmc-svtplay#105]
Most if not all, menu entries results in script error.
                                            Traceback (most recent call last):
                                              File "/storage/.xbmc/addons/plugin.video.svtplay/default.py", line 364, in <module>
                                                viewEpisodes(ARG_URL)
                                              File "/storage/.xbmc/addons/plugin.video.svtplay/default.py", line 172, in viewEpisodes
                                                episodes = svt.getEpisodes(url)
                                              File "/storage/.xbmc/addons/plugin.video.svtplay/resources/lib/svt.py", line 280, in getEpisodes
                                                return getArticles(SECTION_EPISODES, url)
                                              File "/storage/.xbmc/addons/plugin.video.svtplay/resources/lib/svt.py", line 329, in getArticles
                                                ret = "href")[0]
                                            IndexError: list index out of range

**Comment by kokangit** [comment]
There is a fix in svt.py in my fork:
https://github.com/kokangit/xbmc-svtplay

**Comment by linqcan** [comment]
Please do a pull request against the "gotham" branch. That would speed
things up.

**Comment by kokangit** [comment]
Absolut! Jag gör det under dagen.
Edit: done!

**Comment by linqcan** [comment]
Fixed. Will not request a xbmc update until end of the day in case there are more changes coming from SVT during the day.
