### ISSUE TITLE
Add to favorites not working

### ISSUE THREAD

**Issue by pacmyc** [kodi-svtplay/xbmc-svtplay#114]
Add to favorites (by using contextmenu button) doesnt work and produces the following error:

 ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: (2, 'No such file or directory', '/home/pi/.xbmc/userdata/addon_data/plugin.video.svtplay/favorites.json')
                                            Traceback (most recent call last):
                                              File "/home/pi/.xbmc/addons/plugin.video.svtplay/resources/lib/FavoritesManager.py", line 92, in <module>
                                                add(sys.argv[2], sys.argv[3])
                                              File "/home/pi/.xbmc/addons/plugin.video.svtplay/resources/lib/FavoritesManager.py", line 24, in add
                                                __save_to_disk()
                                              File "/home/pi/.xbmc/addons/plugin.video.svtplay/resources/lib/FavoritesManager.py", line 82, in __save_to_disk
                                                with open(FILE_PATH, "w") as file_handle:
                                            IOError: (2, 'No such file or directory', '/home/pi/.xbmc/userdata/addon_data/plugin.video.svtplay/favorites.json')
                                            -->End of Python script error report<--

**Comment by pacmyc** [comment]
Got it working now after opening the configuration menu and then restarting the plugin. (the folder .xbmc/userdata/addon_data/plugin.video.svtplay seems to be created only when the settings-menu is loaded.)

**Comment by linqcan** [comment]
Strange. Which platform is this?

**Comment by pacmyc** [comment]
Latest Raspbmc build on raspberry pi

**Comment by linqcan** [comment]
Thanks!
Will try to reproduce.
