### ISSUE TITLE
Exception for Group programs in A-Ö by first character

### ISSUE THREAD

**Issue by kokangit** [kodi-svtplay/xbmc-svtplay#121]
22:49:25 T:154267648   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/var/mobile/Library/Preferences/XBMC/addons/plugin.video.svtplay/default.py", line 378, in <module>
                                                viewProgramsByLetter(ARG_PARAMS.get("letter"))
                                              File "/var/mobile/Library/Preferences/XBMC/addons/plugin.video.svtplay/default.py", line 114, in viewProgramsByLetter
                                                programs = svt.getProgramsByLetter(letter)
                                              File "/var/mobile/Library/Preferences/XBMC/addons/plugin.video.svtplay/resources/lib/svt.py", line 161, in getProgramsByLetter
                                                heading = common.parseDOM(letterbox, "h3")[0]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--

A working pattern for letterboxes:
  letterboxes = common.parseDOM(html, "li", attrs = { "class": "[^\"']_play_alphabetic-list__letter-container[^\"']_" })

**Comment by linqcan** [comment]
Must have been a temporary fluke?
Test case work and I don't have any issues with 4.0.12.

Are you still seeing this?

**Comment by oscar-b** [comment]
I'm still seeing problems with this:

```
22:35:34 T:140432130434816   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/.xbmc/addons/plugin.video.svtplay/default.py", line 378, in <module>
                                                viewProgramsByLetter(ARG_PARAMS.get("letter"))
                                              File "/storage/.xbmc/addons/plugin.video.svtplay/default.py", line 114, in viewProgramsByLetter
                                                programs = svt.getProgramsByLetter(letter)
                                              File "/storage/.xbmc/addons/plugin.video.svtplay/resources/lib/svt.py", line 161, in getProgramsByLetter
                                                heading = common.parseDOM(letterbox, "h3")[0]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
22:35:34 T:140433044821888   ERROR: GetDirectory - Error getting plugin://plugin.video.svtplay/?letter=R&mode=letter
22:35:34 T:140433044821888   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.svtplay/?letter=R&mode=letter) failed
```

**Comment by kokangit** [comment]
Yes, still problems. Note that choosing A works, but rest gives error. Settings must be true for grouping A-Ö.

**Comment by linqcan** [comment]
Yup, seeing it now!
Fixing it now.

**Comment by linqcan** [comment]
Fix on the way. Thanks for reporting!
@kokangit @oscar-b
