### ISSUE TITLE
Popular and latest prorgrams not working.

### ISSUE THREAD

**Issue by anarfox** [kodi-svtplay/xbmc-svtplay#154]
Get error "SVT Play error - Check the log for more information."
Log says:
`16:11:15 T:20204 WARNING: Previous line repeats 2 times.
16:11:15 T:20204   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "C:\Users\anarfox\AppData\Roaming\Kodi\addons\plugin.video.svtplay\default.py", line 368, in <module>
                                                viewSection(ARG_MODE, int(ARG_PAGE))
                                              File "C:\Users\anarfox\AppData\Roaming\Kodi\addons\plugin.video.svtplay\default.py", line 122, in viewSection
                                                (items, moreItems) = svt.getItems(section, page)
                                              File "C:\Users\anarfox\AppData\Roaming\Kodi\addons\plugin.video.svtplay\resources\lib\svt.py", line 352, in getItems
                                                plot = plots[index]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
16:11:15 T:13144   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.svtplay/?mode=populara
16:11:15 T:13144   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.svtplay/?mode=populara) failed`

**Comment by anarfox** [comment]
Double post. >_<
