### ISSUE TITLE
Stopped working in OSMC

### ISSUE THREAD

**Issue by Sakrecoer** [kodi-svtplay/xbmc-svtplay#157]
About 2 months ago, the plugin stopped working on kodi that is distrobuted by OSMC. I get the suspicion that it has something to do with https, but i'm too unexperienced to know for sure. 

Since i can see this git being actively developped, i figure this might be something on the osmc side, not distributing an updated version. However, i thought i'd let you know....

If there is anything you can do about and need from me in order to do so, let me know :)

Thanks for this plugin however!

**Comment by Sakrecoer** [comment]
If this can help....

```
$ python2.7 -m unittest tests/testSvt.py 
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/unittest/__main__.py", line 12, in <module>
    main(module=None)
  File "/usr/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
ImportError: Import by filename is not supported.
```

**Comment by linqcan** [comment]
Regarding the log you pasted. You are running the tests incorrectly. See
the Readme file for how to run them.

Please post a log from kodi or failing unit tests here and I will have a
look.

**Comment by Sakrecoer** [comment]
Thank you!
here is the failing unit test as explained in the readme:

```
$ python -m unittest testSvt
CommonFunctions-1.2.0
[TestSvt] fetchPage : 'called for : {'link': 'http://svtplay.se/program'}'
[TestSvt] fetchPage : 'Got request'
[TestSvt] fetchPage : 'connecting to server...'
[TestSvt] fetchPage : 'Done'
.[TestSvt] fetchPage : 'called for : {'link': 'http://svtplay.se/program'}'
[TestSvt] fetchPage : 'Got request'
[TestSvt] fetchPage : 'connecting to server...'
[TestSvt] fetchPage : 'Done'
[TestSvt] errorMsg : 'Error: Could not find container'
F[TestSvt] fetchPage : 'called for : {'link': 'http://svtplay.se/program'}'
[TestSvt] fetchPage : 'Got request'
[TestSvt] fetchPage : 'connecting to server...'
[TestSvt] fetchPage : 'Done'
[TestSvt] errorMsg : 'Error: No container found!'
F[TestSvt] fetchPage : 'called for : {'link': 'http://svtplay.se/kanaler'}'
[TestSvt] fetchPage : 'Got request'
[TestSvt] fetchPage : 'connecting to server...'
[TestSvt] fetchPage : 'Done'
[TestSvt] errorMsg : 'Error: No container found for channels'
F[TestSvt] fetchPage : 'called for : {'link': 'http://svtplay.se/agenda?sida=2'}'
[TestSvt] fetchPage : 'Got request'
[TestSvt] fetchPage : 'connecting to server...'
[TestSvt] fetchPage : 'Done'
.[TestSvt] fetchPage : 'called for : {'link': 'http://svtplay.se/agenda?sida=2'}'
[TestSvt] fetchPage : 'Got request'
[TestSvt] fetchPage : 'connecting to server...'
[TestSvt] fetchPage : 'Done'
[TestSvt] infoMsg : 'Info: Skipping live item!'
.[TestSvt] fetchPage : 'called for : {'link': 'http://svtplay.se/nyheter'}'
[TestSvt] fetchPage : 'Got request'
[TestSvt] fetchPage : 'connecting to server...'
[TestSvt] fetchPage : 'Done'
.[TestSvt] fetchPage : 'called for : {'link': 'http://svtplay.se/program'}'
[TestSvt] fetchPage : 'Got request'
[TestSvt] fetchPage : 'connecting to server...'
[TestSvt] fetchPage : 'Done'
[TestSvt] errorMsg : 'Error: No containers found for letter 'A''
F[TestSvt] fetchPage : 'called for : {'link': 'http://svtplay.se/program'}'
[TestSvt] fetchPage : 'Got request'
[TestSvt] fetchPage : 'connecting to server...'
[TestSvt] fetchPage : 'Done'
[TestSvt] errorMsg : 'Error: Could not find container'
E[TestSvt] fetchPage : 'called for : {'link': 'http://svtplay.se/sok?q=agenda'}'
[TestSvt] fetchPage : 'Got request'
[TestSvt] fetchPage : 'connecting to server...'
[TestSvt] fetchPage : 'Done'
[TestSvt] errorMsg : 'Error: No container found for list ID '[^"']*playJs-search-titles[^"']*''
[TestSvt] errorMsg : 'Error: No items in list '[^"']*playJs-search-titles[^"']*''
[TestSvt] errorMsg : 'Error: No container found for list ID '[^"']*playJs-search-episodes[^"']*''
[TestSvt] errorMsg : 'Error: No items in list '[^"']*playJs-search-episodes[^"']*''
[TestSvt] errorMsg : 'Error: No container found for list ID '[^"']*playJs-search-clips[^"']*''
[TestSvt] errorMsg : 'Error: No items in list '[^"']*playJs-search-clips[^"']*''
F
======================================================================
ERROR: test_programs_for_category (testSvt.TestSvtModule)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testSvt.py", line 46, in test_programs_for_category
    for category in categories:
TypeError: 'NoneType' object is not iterable

======================================================================
FAIL: test_categories (testSvt.TestSvtModule)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testSvt.py", line 37, in test_categories
    self.assertHasContent(categories)
  File "testSvt.py", line 19, in assertHasContent
    self.fail("List is None")
AssertionError: List is None

======================================================================
FAIL: test_get_alphas (testSvt.TestSvtModule)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testSvt.py", line 59, in test_get_alphas
    self.assertHasContent(alphas)
  File "testSvt.py", line 19, in assertHasContent
    self.fail("List is None")
AssertionError: List is None

======================================================================
FAIL: test_get_channels (testSvt.TestSvtModule)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testSvt.py", line 88, in test_get_channels
    self.assertHasContent(items)
  File "testSvt.py", line 19, in assertHasContent
    self.fail("List is None")
AssertionError: List is None

======================================================================
FAIL: test_programs_by_letter (testSvt.TestSvtModule)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testSvt.py", line 67, in test_programs_by_letter
    self.assertHasContent(programs)
  File "testSvt.py", line 19, in assertHasContent
    self.fail("List is None")
AssertionError: List is None

======================================================================
FAIL: test_search_results (testSvt.TestSvtModule)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testSvt.py", line 79, in test_search_results
    self.assertHasContent(items)
  File "testSvt.py", line 22, in assertHasContent
    self.fail("List is empty")
AssertionError: List is empty

----------------------------------------------------------------------
Ran 10 tests in 47.785s

FAILED (failures=5, errors=1)
```

unfortunately, i find nothing for svtplay in the kodi.log. Created a fresh log file and produced the error: osmc tells me to check the logs but there is nothing printed to it...

Let me know if there anything else i can do or provide to help out.

**Comment by linqcan** [comment]
Which version of the plugin are you running?

**Comment by perrylof** [comment]
I have the same issue, running plugin version 4.0.21

**Comment by linqcan** [comment]
That's an old and broken version. The latest is 4.0.26. Try updating the
plug-in.

**Comment by Sakrecoer** [comment]
i'm struggling to find out the version. i'm using the one that is in the osmc repository...

**Comment by rikardfalkeborn** [comment]
My OSMC reports the latest version from repos as 4.0.21. Running 4.0.26 works fine, so I'd say OSMC is not synching things correctly.

**Comment by perrylof** [comment]
Indeed, that's the problem. I never checked the version number, just assumed running the update from OSMC would get me the lastest version.

EDIT: Fixed by forcing updates. Could not find how to update in OSMC skin, had to change skin to Confluence to access the update button.

**Comment by linqcan** [comment]
Please note that only the official Kodi release/distribution is the
supported platform. All other variants and (re)distributions are
unsupported.

In this particular case you need to turn to your distribution's support
channels.

Close #157
