### ISSUE TITLE
Playlist manager is broken, cannot add episode to playlist

### ISSUE THREAD

**Issue by linqcan** [kodi-svtplay/xbmc-svtplay#176]
```
Error Type: <type 'exceptions.AttributeError'>
Error Contents: 'module' object has no attribute 'resolveShowURL'
Traceback (most recent call last):
File "/home/erik/.kodi/addons/plugin.video.svtplay/resources/lib/PlaylistManager.py", line 74, in <module>
  add(sys.argv[2], sys.argv[3], sys.argv[4])
File "/home/erik/.kodi/addons/plugin.video.svtplay/resources/lib/PlaylistManager.py", line 14, in add
  list_item = __create_list_item(url, title, thumbnail)
File "/home/erik/.kodi/addons/plugin.video.svtplay/resources/lib/PlaylistManager.py", line 55, in      __create_list_item
video_url = __get_video_url(url)
File "/home/erik/.kodi/addons/plugin.video.svtplay/resources/lib/PlaylistManager.py", line 62, in __get_video_url
show_obj = helper.resolveShowURL(url)
AttributeError: 'module' object has no attribute 'resolveShowURL'
```

**Comment by linqcan** [comment]
Playlist manager will be removed when moving to v17 support only as the playlist manager in Kodi v17 superseeds our own.

**Comment by linqcan** [comment]
Removed in 7f5f194b27ccd98ed346521e588cd2371572a1b2 to reduce complexity.
