### ISSUE TITLE
Programs that have a security warning will not play

### ISSUE THREAD

**Issue by M1ch43lk** [kodi-svtplay/xbmc-svtplay#199]
Programs that have a security warning will not play
 
Example:

https://www.svtplay.se/video/12966984/ett-rop-fran-syrien/dokument-utifran-ett-rop-fran-syrien-ett-rop-fran-syrien

Any hints why?

Thanks in advance

22:50:13 T:140510395430656  NOTICE: [SVT Play 4.0.46] <module> : 'params: {'url': '%2fvideo%2f12966984%2fett-rop-fran-syrien%2fdokument-utifran-ett-rop-fran-syrien-ett-rop-fran-syrien', 'mode': 'pr'}'
22:50:14 T:140510395430656   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'simplejson.scanner.JSONDecodeError'>
                                            Error Contents: Expecting value: line 1 column 1 (char 0)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.svtplay/default.py", line 368, in <module>
                                                viewEpisodes(ARG_URL)
                                              File "/storage/.kodi/addons/plugin.video.svtplay/default.py", line 167, in viewEpisodes
                                                episodes = svt.getEpisodes(url)
                                              File "/storage/.kodi/addons/plugin.video.svtplay/resources/lib/svt.py", line 238, in getEpisodes
                                                article_id = __get_article_id_for_title(title)
                                              File "/storage/.kodi/addons/plugin.video.svtplay/resources/lib/svt.py", line 345, in __get_article_id_for_title
                                                json_data = __get_json(url)
                                              File "/storage/.kodi/addons/plugin.video.svtplay/resources/lib/svt.py", line 374, in __get_json
                                                return response.json()
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 850, in json
                                                return complexjson.loads(self.text, **kwargs)
                                              File "/usr/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
                                              File "/usr/lib/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
                                              File "/usr/lib/python2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
                                            JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                            -->End of Python script error report<--
22:50:14 T:140511788316736   ERROR: GetDirectory - Error getting plugin://plugin.video.svtplay/?mode=pr&url=%2fvideo%2f12966984%2fett-rop-fran-syrien%2fdokument-utifran-ett-rop-fran-syrien-ett-rop-fran-syrien
22:50:14 T:140511788316736   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.svtplay/?mode=pr&url=%2fvideo%2f12966984%2fett-rop-fran-syrien%2fdokument-utifran-ett-rop-fran-syrien-ett-rop-fran-syrien) failed

**Comment by linqcan** [comment]
Thanks for reporting this!
Looks like videos and programs (listing) are getting mixed up suddenly.
Please the steps needed to reproduce, that is; how you got here.

**Comment by M1ch43lk** [comment]
Basiclly just try to play the documentery with the addon.

Step1: Find the documentary "_Ett rop från Syrien_" (Under "popular" or "dokument utifrån")
Step2: Try to play it (will probably fail)

Other documentary on this [page ](https://www.svtplay.se/video/12966984/ett-rop-fran-syrien/dokument-utifran-ett-rop-fran-syrien-ett-rop-fran-syrien)will play just fine.

Certain programs have "child" [protection ](https://kundo.se/org/svt-play-hjalp/d/barnskydd-14/)for violent or sexually explicit scenes...The addon does not seem to be able to handle them.

**Comment by linqcan** [comment]
Ok, thanks for the information!
Looks like they have changed a few things in their end. Will look into it
soon.
Meanwhile, does it work if you search for the item and try to play it from
there?

**Comment by M1ch43lk** [comment]
_>Meanwhile, does it work if you search for the item and try to play it from there?_

Unfortunatly not :(

**Comment by linqcan** [comment]
First change that will fix this, I hope. 2534ce3a2d2f678f8a37aa2a1100695578929145

Found another error however, fix will land soon. Sorry about the delay!

**Comment by M1ch43lk** [comment]
Thanks! Will try it out this evening.

**Comment by M1ch43lk** [comment]
Just tested and it works great! :+1: 

Thanks again!

**Comment by linqcan** [comment]
Ah, thanks for testing!
