### ISSUE TITLE
Python 3 migration

### ISSUE THREAD

**Issue by linqcan** [kodi-svtplay/xbmc-svtplay#237]
Collection of issues found during exploration with Python 3 builds. Own tracking only, therefore locked.

Kodi PR for merge of Python 3: https://github.com/xbmc/xbmc/pull/16116

**Comment by linqcan** [comment]
script.module.parsedom\lib\CommonFunctions.py

Replace dependency with own code.

```
2019-07-14 10:53:10.702 T:14448   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'SyntaxError'>
                                            Error Contents: Missing parentheses in call to 'print'. Did you mean print(plugin)? (CommonFunctions.py, line 32)
                                            Traceback (most recent call last):
                                              File "C:\Users\erikaathome\AppData\Roaming\Kodi\addons\plugin.video.svtplay\default.py", line 13, in <module>
                                                import CommonFunctions as common
                                              File "C:\Users\erikaathome\AppData\Roaming\Kodi\addons\script.module.parsedom\lib\CommonFunctions.py", line 32
                                                print plugin
                                                           ^
                                            SyntaxError: Missing parentheses in call to 'print'. Did you mean print(plugin)?
                                            -->End of Python script error report<--

```

**Comment by linqcan** [comment]
Branch krypton should now support Python 3. Tested against local Kodi 19.x test build.
