### ISSUE TITLE
Cant cast to kodi from phone or laptop

### ISSUE THREAD

**Issue by pomah86** [kodi-svtplay/xbmc-svtplay#260]
Using the chrome add-on "Play to kodi" or the app "Yatse" I can not "cast" a program to kodi as I could before.

# Problem description
Opening the "svtplay.se" website or app on laptop or phone and trying to "cast" the program I want to watch results in an error "failed to play, check log"

See above
# Steps to reproduce

* Open svtplay.se
* Choose what program to watch
* Click on the "play to kodi" icon in chrome (install and configure if you do not have since before)

# System information
Kodi version: 
18.6 Git: 18.6-Leia, compiled 2020-03-22

Platform: 
Libreelec, Intel Nuc

Plugin version: 
nilzen - 5.1.9

# Log

2020-05-10 09:23:41.674 T:140259684968192   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.svtplay/default.py", line 12, in <module>
                                                svt_play.run(PLUGIN_PARAMS)
                                              File "/storage/.kodi/addons/plugin.video.svtplay/resources/lib/svtplay.py", line 74, in run
                                                self.navigate(arg_mode, arg_id, arg_params)
                                              File "/storage/.kodi/addons/plugin.video.svtplay/resources/lib/svtplay.py", line 103, in navigate
                                                self.start_video(id)
                                              File "/storage/.kodi/addons/plugin.video.svtplay/resources/lib/svtplay.py", line 222, in start_video
                                                legacy_id = video_url.split("/")[2]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--

**Comment by linqcan** [comment]
This is not an issue with this plugin but with the "Play to Kodi" chrome addon. They are trying to start this addon with incorrect parameters.
Please file an issue in their repository.

**Comment by pomah86** [comment]
But it is the same behaviour when trying to play an episode using e.g. the "kore" app.

**Comment by linqcan** [comment]
Then they are probably using the wrong parameters as well. You should
contact them too if this is a feature you want working.
Let me know if you find out anything useful! 👍🏻

**Comment by o010b** [comment]
Sorry for duplicate spam. Accidentally made a pull request to my own fork first.
